@echo off
SET ORIG_PATH=%PATH%

SET BASE_LINK_DIR=C:/Users/miclomba/source/repos/Backend/X/out/build/x64-Debug
SET DATABASE_ADAPTERS=%BASE_LINK_DIR%/DatabaseAdapters
SET ENTITIES=%BASE_LINK_DIR%/Entities
SET ENTITIESMODULE=%BASE_LINK_DIR%/EntitiesModule
SET EVENTS=%BASE_LINK_DIR%/Events
SET FILESYSTEM_ADAPTERS=%BASE_LINK_DIR%/FilesystemAdapters
SET INTERPROCESS=%BASE_LINK_DIR%/Interprocess
SET INTRAPROCESS=%BASE_LINK_DIR%/Intraprocess
SET RESOURCES=%BASE_LINK_DIR%/Resources

SET PATH=%PATH%;%DATABASE_ADAPTERS%;%ENTITIES%;%ENTITIESMODULE%;%EVENTS%;%FILESYSTEM_ADAPTERS%;%INTERPROCESS%;%INTRAPROCESS%;%RESOURCES%

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv.exe"

SET PATH=%ORIG_PATH%